sudo: required
language: go
go:
- 1.13.x
script:
- make dist
before_deploy:
- "./ci/hashgen.sh"
deploy:
  api_key:
    secure: VedDISGwlkOhc/i8Z6zyfea/0+OpSfIbqxJzH6PyCli9WgTxAL2Ci1Ye6tFz2zO810RhhkZ43UAvqZu0MAZS+0WBetIN/wqCj2zD6vps8Cfe+UV5Xs3L34F9K4iNShy3Nkbz5t0ulN5OShocA4vQlWOCqklOOW7dgfDnsQcdXLMzFKdnrOa1B3FVNEynXXv5c7z6tPHftnJbJ2DrC+VQgRC1Npsez7IJnqo1b9IWEQCvE4E7u1IQtK5PuZ0ApeKTAwLTh5JHPbstjom3o086YQ+06aQtApp1jqi9hvF0edNgCKut+okQrveTwtDTPIsXknx+IJtcl0x32WeKcX7QbMfDFTFAqOTRsCDQWA/zHEHHKx6W0CAe5HIHiL5uIVijsRo/1y3FU2s+yu8odJXEQIDfmHGUJWmUiYWY4McMCsUzJ4GlXpfGR1ddKbwN6VoBfQt1eBbd8vMj2DaF4bWDkbKi9AJ+HTEGZmL6mJVBJgQ/ZNlenQp7YXiAL14CKSlmHuTg86rYIfgaj9NUSWeCTqNgG9n7ZBpg3ocZdpGJf55WtYJIOhbas9tNJsVM3iCRmFH0TMYgL1iYE4C+Mpa9vXOWYxtC3Dhb4ROHUmYiVMtcZ2x5H/9sTEG2gvg39tFgvISd/SffFx3Xpi06H0HDw4I85xGPeRkVLVnSzJSBh54=
  provider: releases
  file:
  - "./bin/inletsctl.tgz"
  - "./bin/inletsctl.sha256"
  - "./bin/inletsctl.tgz.sha256"
  - "./bin/inletsctl-darwin.tgz"
  - "./bin/inletsctl-darwin.sha256"
  - "./bin/inletsctl-darwin.tgz.sha256"
  - "./bin/inletsctl-armhf.tgz"
  - "./bin/inletsctl-armhf.sha256"
  - "./bin/inletsctl-armhf.tgz.sha256"
  - "./bin/inletsctl-arm64.tgz"
  - "./bin/inletsctl-arm64.sha256"
  - "./bin/inletsctl-arm64.tgz.sha256"
  - "./bin/inletsctl.exe.tgz"
  - "./bin/inletsctl.exe.sha256"
  - "./bin/inletsctl.exe.tgz.sha256"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
env:
  matrix:
  - GO111MODULE=on
